<?php

########################################################################
# Extension Manager/Repository config file for ext: "g40cloudfile"
#
# Auto generated by Extension Builder 2012-04-14
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cloud File Manager',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Frei',
	'author_email' => 'df@gate40.net',
	'author_company' => 'gate40 websolutions',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>